<h1>Teoria de Grafos</h1>

Los grafos son estructuras discretas que consisten de vértices y
aristas que conectan los vértices. Existen disintos tipos de grafos,
dependiendo si las aristas tienen o no dirección, si existen múltiples
aristas para un mismo vértices o si se permiten o no lazos.

Un grafo es una tupla $G = (V , E )$ donde $V$ es un conjunto (finito o
infinito) de vértices y E es un cuna colección finita de aristas. El
conjunto E contiene elementos de la unión de todos los subconjuntos con
uno o dos elementos del conjunto $V$ . Esto quiere decir, que cada
elemento de E es un subconjunto de uno o dos elementos de $V$ .



In [2]:
import numpy as np

class abstract_graph:
    
    def __init__(self,_edges):
        self.edges=_edges
        self.nodes={u for u,v in self.edges} | {v for u,v in self.edges}
        
    def adjacency_matrix(self):
        pass
    
    def adjacency_list(self):
        pass

Un grafo simple es un grafo en el cual existe sólo una arista $(u, v)$ para
conectar dos vértices $u$ y $v$ .

In [4]:
class simple_graph(abstract_graph):
    
    def __init__(self,_edges):
        tmp=[]
        for (u,v) in _edges:
            if (v,u) not in tmp and v!=u:
                tmp.append((u,v))
        self.edges=tmp
        self.nodes={u for u,v in _edges} | {v for u,v in _edges}
     
    def adjacency_matrix(self):
        # completar
        n=len(self.nodes)
        mat=np.zeros((n,n))
        for i,v in enumerate(self.nodes):
            for j,k in enumerate(self.nodes):
                if (v,k) in self.edges:
                    mat[i,j]=1
                    mat[j,i]=1
        return mat
    
    
    def adjacency_list(self):
        adjacent=lambda n : {v for u,v in self.edges if u==n } | {u for u,v in self.edges if v==n}
        return {v:adjacent(v) for v in self.nodes}
        
    

E=[('A','B'),('C','D'),('B','D'),('B','A'),('A','A')]
G=simple_graph(E)
print('aristas',G.edges)
print('nodos : ',G.nodes)
print('matriz adyacencia : ',G.adjacency_matrix())
print('lista adyacencia : ',G.adjacency_list())

aristas [('A', 'B'), ('C', 'D'), ('B', 'D')]
nodos :  {'D', 'B', 'C', 'A'}
matriz adyacencia :  [[0. 1. 1. 0.]
 [1. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
lista adyacencia :  {'D': {'B', 'C'}, 'B': {'A', 'D'}, 'C': {'D'}, 'A': {'B'}}


Un multi-grafo simple es un grafo en el cual existe más de una arista
$(u, v)$ para conectar dos vértices $u$ y $v$ (aristas paralelas y lazos).

In [13]:
class multi_graph(abstract_graph):
    

    def adjacency_matrix(self):
        # completar
        pass
    
    def adjacency_list(self):
        # completar
        pass
    
E2=[(1,2),(3,4),(2,4),(1,2),(1,1)]
G2=multi_graph(E2)
print('nodos : ',G2.nodes)
print('aristas : ',G2.edges)
print('matriz adyacencia : ',G2.adjacency_matrix())
print('lista adyacencia : ',G2.adjacency_list())

nodos :  {1, 2, 3, 4}
aristas :  [(1, 2), (3, 4), (2, 4), (1, 2), (1, 1)]
matriz adyacencia :  None
lista adyacencia :  None


Un grafo dirigido es un grafo en el cual cada arista $(u,v)$ consiste en un
par ordenado de vértices $u$ y $v$.

In [19]:
class digraph(abstract_graph):
    
    def __init__(self,_edges):
        tmp=[]
        for (u,v) in _edges:
            if (v,u) not in tmp:
                tmp.append((u,v))
        self.edges=tmp
        self.nodes={u for u,v in self.edges} | {u for u,v in self.edges}

        
    def adjacency_matrix(self):
        # completar
        pass
    
    def adjacency_list(self):
        # completar
        pass
    

E3=[(1,2),(3,4),(2,4),(2,1),(2,1)]
G3=digraph(E3)
print('nodos : ',G3.nodes)
print('aristas : ',G3.edges)
print('lista adyacencia : ',G3.adjacency_list())

nodos :  {1, 2, 3}
aristas :  [(1, 2), (3, 4), (2, 4)]
lista adyacencia :  None


In [20]:
class weighted_graph(abstract_graph):
    
    def __init__(self,_edges):
        self.edges=_edges
        self.nodes={u for u,v in self.edges.keys()} | {v for u,v in self.edges.keys()}
        
    def adjacency_matrix(self):
        # completar
        n=len(self.nodes)
        mat=np.zeros((n,n))
        return mat
    
    def adjacency_list(self):
        adjacent=lambda n : {v for u,v in self.edges.keys() if u==n } | {u for u,v in self.edges.keys() if v==n}
        return {v:adjacent(v) for v in self.nodes}
        
 

In [21]:
E4={(1,2):1,(3,4):2,(2,4):1}
G4=weighted_graph(E4)
print('nodos : ',G4.nodes)
print(G4.adjacency_matrix())
print('lista adyacencia : ',G4.adjacency_list())

nodos :  {1, 2, 3, 4}
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
lista adyacencia :  {1: {2}, 2: {1, 4}, 3: {4}, 4: {2, 3}}


# Tarea

    1.) Utilizar clase 'simple_graph' para crear un grafo completo simple con 10 nodos (Usar producto cartesiano para crear lista de aristas)

    2.) Utilizar clase 'digraph' para crear un grafo dirigido simple con 10 nodos.